from typing import Optional
from pydantic import BaseModel, Field, model_validator


class UserCreate(BaseModel):
    user: str = Field(description="Username")
    password: str = Field(description="Password as plain text (stored hashed)")
    role: str = Field(default="client", description="Role of the user")


class UserOut(BaseModel):
    id: int = Field(description="User ID autogenerated by the database")
    user: str = Field(description="Username")
    role: str = Field(description="Role of the user")


class UserId(BaseModel):
    id: Optional[int] = Field(None, description="User ID autogenerated by the database")
    user: Optional[str] = Field(None, description="Username")

    @model_validator(mode="before")
    def check_at_least_one(values):
        if values.get("id") is None and values.get("user") is None:
            raise ValueError("At least 'id' or 'user' must be provided")
        return values
